diff a/arch/arm/boot/dts/Makefile b/arch/arm/boot/dts/Makefile	(rejected hunks)
@@ -183,6 +183,8 @@ dtb-$(CONFIG_ARCH_MXC) += \
 	imx6q-sabresd-uart.dtb \
 	imx6q-sabresd-hdcp.dtb \
 	imx6q-sabresd-ldo.dtb \
+	imx6q-yygd.dtb \
+	imx6q-yygd-ldo.dtb \
 	imx6q-sbc6x.dtb \
 	imx6q-udoo.dtb \
 	imx6q-wandboard.dtb \
